name: End to end tests (Cypress)

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ”
        uses: actions/checkout@v4

      - name: Set up node env
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16
                  
      # Install NPM dependencies, cache them correctly
      # and run all Cypress End to End tests
      - name: Run End to End tests ğŸ§ª
        uses: cypress-io/github-action@v6
        with:
          build: npm run generate
          start: npm start
          component: false

